name: Test Runback Script

on:
  push:
    paths:
      - 'runback'
      - '.github/workflows/test-runback.yml'
  pull_request:
    paths:
      - 'runback'
      - '.github/workflows/test-runback.yml'

jobs:
  test-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.9.6

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Make script executable
      if: runner.os != 'Windows'
      run: chmod +x runback

    - name: Test script help command
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./runback
        else
          ./runback
        fi

    - name: Test build command
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./runback build
        else
          ./runback build
        fi

    - name: Test database commands
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./runback db:start
          sleep 10
          ./runback db:stop
        else
          ./runback db:start
          sleep 10
          ./runback db:stop
        fi

    - name: Test application commands
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./runback start &
          sleep 10
          ./runback stop
        else
          ./runback start &
          sleep 10
          ./runback stop
        fi 