services:
  mysql:
    image: mysql:8.0
    container_name: resa-mysql
    environment:
      MYSQL_DATABASE: resa
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 20s
      retries: 10
    restart: unless-stopped 

volumes:
  mysql_data: